name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    env:
      PSYCHEDELIC_ORG_NPM_PKG_TOKEN: ${{ secrets.PSYCHEDELIC_ORG_NPM_PKG_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Grant packages read
        run: echo "//npm.pkg.github.com/:_authToken=$PSYCHEDELIC_ORG_NPM_PKG_TOKEN" >> .npmrc

      - name:  Grant packages read
        run:   |
              if [ "$RUNNER_OS" == "Linux" ]; then
                    echo "//npm.pkg.github.com/:_authToken=$PSYCHEDELIC_ORG_NPM_PKG_TOKEN" >> .npmrc
              elif [ "$RUNNER_OS" == "macOS" ]; then
                    echo "//npm.pkg.github.com/:_authToken=$PSYCHEDELIC_ORG_NPM_PKG_TOKEN" >> .npmrc
              elif [ "$RUNNER_OS" == "Windows" ]; then
                    echo "//npm.pkg.github.com/:_authToken=$PSYCHEDELIC_ORG_NPM_PKG_TOKEN" > .npmrc
              else
                    echo "$RUNNER_OS not supported"
                    exit 1
              fi
        shell: bash
      
      - name: Test NPMRC
        run: cat .npmrc

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
